
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: mia-reader
email: victoria.022@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  This is a mirror of the Marxists Internet Archive Reader. It is a collection of Marxist texts, including works by Marx, Engels, Lenin, Trotsky, Luxemburg, Plekhanov, Bukharin, Stalin, Mao, Gramsci, Fanon, and many others.
  This mirror specifically contains the English selected works for now.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown

nav_links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

favicon: /assets/img/favicon.ico

nav_external_links:
  - title: Marxists Internet Archive
    url: https://www.marxists.org/
    hide_icon: false

# Build settings
theme: just-the-docs
color_scheme: dark

gems:
- jekyll-font-awesome-sass
- jekyll-feed  

include:
  - _pages

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#''
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/